
import java.io.Serializable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vineetarora
 */
public class deletestore extends javax.swing.JFrame  implements Serializable{
private static String id;
    /**
     * Creates new form deletestore
     */
    public deletestore(String id) {
        initComponents();
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel1.setText("Deletion");

        jLabel2.setText("What do you want to delete");

        jRadioButton1.setText("Category");

        jRadioButton2.setText("Subcategory");

        jRadioButton3.setText("Product");

        jLabel3.setText("Name");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(39, 39, 39)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(88, 88, 88)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        new managestore(id).setVisible(true);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(jRadioButton3.isSelected()){
            String name=jTextField1.getText();
            Connection conn=null;
            PreparedStatement p=null;
            
            try{
                conn=configwarehouseadmin.getConnection1();
                p=conn.prepareStatement("delete from PRODUCT where NAME=? and OPTIONS=? and ID=?");
                p.setString(1, name);
                p.setString(2, "Store");
                p.setString(3, id);
                if(p.executeUpdate()==1){
                    JOptionPane.showMessageDialog(rootPane, "Deleted!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Product with this name doesn't exist!");
                }
                conn.close();
                jTextField1.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        else if(jRadioButton2.isSelected()){
            String name=jTextField1.getText();
            Connection conn=null;
            PreparedStatement p=null;
            
            try{
                conn=configwarehouseadmin.getConnection1();
                p=conn.prepareStatement("delete from PRODUCT where SUBCATEGORY=? and OPTIONS=? and ID=?");
                p.setString(1, name);
                p.setString(2, "Store");
                p.setString(3, id);
                if(p.executeUpdate()==1){
                    JOptionPane.showMessageDialog(rootPane, "Deleted all products in this subcategory!");
                }
                else{
                    
                }
                conn.close();
                p=null;
                conn=configwarehouseadmin.getConnection1();
                p=conn.prepareStatement("delete from SUBCATEGORY where NAME=? and OPTIONS=? and ID=?");
                p.setString(1, name);
                p.setString(2, "Store");
                p.setString(3, id);
                if(p.executeUpdate()==1){
                    JOptionPane.showMessageDialog(rootPane, "Deleted Subcategory!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Subcategory with this name doesn't exist!");
                }
                conn.close();
                jTextField1.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        else if(jRadioButton1.isSelected()){
            String name=jTextField1.getText();
            Connection conn=null;
            PreparedStatement p=null;
            
            try{
                conn=configwarehouseadmin.getConnection1();
                p=conn.prepareStatement("delete from PRODUCT where CATEGORY=? and OPTIONS=? and ID=?");
                p.setString(1, name);
                p.setString(2, "Store");
                p.setString(3, id);
                if(p.executeUpdate()==1){
                    JOptionPane.showMessageDialog(rootPane, "Deleted all products in this category!");
                }
                else{
                    
                }
                conn.close();
                p=null;
                conn=configwarehouseadmin.getConnection1();
                p=conn.prepareStatement("delete from SUBCATEGORY where CATEGORY=? and OPTIONS=? and ID=?");
                p.setString(1, name);
                p.setString(2, "Store");
                p.setString(3, id);
                if(p.executeUpdate()==1){
                    JOptionPane.showMessageDialog(rootPane, "Deleted all subcategories in this category!");
                }
                else{
                    //JOptionPane.showMessageDialog(rootPane, "Subcategory with this name doesn't exist!");
                }
                conn.close();
                p=null;
                conn=configwarehouseadmin.getConnection1();
                p=conn.prepareStatement("delete from CATEGORY where NAME=? and OPTIONS=? and ID=?");
                p.setString(1, name);
                p.setString(2, "Store");
                p.setString(3, id);
                if(p.executeUpdate()==1){
                    JOptionPane.showMessageDialog(rootPane, "Deleted Category!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Category with this name doesn't exist!");
                }
                conn.close();
                jTextField1.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletestore(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
